spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/issue_tracker
    username: issue_tracker
    password: changeit
    driverClassName: org.postgresql.Driver